steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-credentials'
  entrypoint: 'gcloud'
  args: ['container', 'clusters', 'get-credentials', '${_CLUSTER_NAME_}', '--project=${_PROJECT_ID_}', '--region=${_REGION_}']
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'kubectl'
  args: ['apply', '-f', '${_ISTIOPATH_}/istio-ingressgateway', '-n', 'asm-ngw-ns']
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'kubectl'
  args: ['apply', '-f', '${_ISTIOPATH_}/istio-egressgateway', '-n', 'asm-ngw-ns']
- name: 'gcr.io/${_PROJECT_ID_}/helm:3.12.0'
  id: 'repo-add-csi'
  entrypoint: 'helm'
  args: ['repo', 'add', 'secrets-store-csi-driver', 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts']
- name: 'gcr.io/${_PROJECT_ID_}/helm:3.12.0'
  id: 'repo-update-csi'
  entrypoint: 'helm'
  args: ['repo', 'update']
  waitFor:
  - 'repo-add-csi'
- name: 'gcr.io/${_PROJECT_ID_}/helm:3.12.0'
  id: 'secrets-store-csi-driver'
  entrypoint: 'helm'
  args: ['upgrade', '--install', 'csi-secrets-store', 'secrets-store-csi-driver/secrets-store-csi-driver', '--set', 'syncSecret.enabled=true', '--set', 'enableSecretRotation=true', '-n',  'kube-system']
  waitFor:
  - 'repo-update-csi'
# FOR PUBLIC GKE CLUSTERS ONLY (OPTIONAL)
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'kubectl'
  args: ['apply', '-f', '${_IPMASQ_CONFIG_PATH_}', '-n', 'kube-system']
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'storage-class'
  entrypoint: 'kubectl'
  args: ['apply', '-f', '${_STORAGE_CLASS_CONFIG_PATH_}']
  waitFor:
  - 'secrets-store-csi-driver'
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'csi-plugin'
  entrypoint: 'kubectl'
  args: ['apply', '-f', '${_CSI_PLUGIN_PATH_}']
  waitFor:
  - 'storage-class'
tags: ['cloud-builders-community']
serviceAccount: "projects/${_PROJECT_ID_}/serviceAccounts/${_PROJECT_ID_}-sa@${_PROJECT_ID_}.iam.gserviceaccount.com"
logsBucket: "gs://${_LOG_BUCKET_}"
substitutions:
  _PROJECT_ID_: ''
  _REGION_: ''
  _CLUSTER_NAME_: ''
  _ISTIOPATH_: ''
  _IPMASQ_CONFIG_PATH_: ''
  _STORAGE_CLASS_CONFIG_PATH_: ''
  _CSI_PLUGIN_PATH_: ''
  _LOG_BUCKET_: ''
options:
    dynamicSubstitutions: true    
