{{ if .Values.csiSecrets }}
{{ $csiSecrets := .Values.csiSecrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $csiSecrets.provider.name }}
spec:
  provider: gcp
  parameters:
    secrets:
    {{ toYaml $csiSecrets.parameters.secrets | nindent 6 }}        
  secretObjects:
  {{ toYaml $csiSecrets.secretObjects | nindent 2 }}
{{ end }}
